# Generated by Django 2.2 on 2021-04-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20201218_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='dt_modified',
        ),
    ]
